config/routes.rb
Rails.application.routes.draw do
  resources :calendars, only: [:index] do
    collection do
      get :callback
      get :events
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authorize_calendar, except: :callback

  rescue_from Google::Apis::AuthorizationError do
    session[:calendar_access_token] = nil
    authorize_calendar
  end

  def index
    @calendar_list = calendar_service.list
  end

  def events
    @events = calendar_service.events(params[:calendar_id], event_params)
  end

  def callback
    client = CalendarService.new.client
    client.code = params[:code]
    response = client.fetch_access_token!
    session[:calendar_access_token] = response

    redirect_to calendars_url
  end

  private

  def authorize_calendar
    return if session[:calendar_access_token].present?
    redirect_to CalendarService.new.authorization_uri
  end

  def calendar_service
    CalendarService.new(session[:calendar_access_token])
  end

  def event_params
    params.permit(:time_min, :time_max)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendars/events.html.erb
<h1>Events</h1>
<%= form_tag events_calendars_path, method: :get do %>
  <%= hidden_field_tag :calendar_id, params[:calendar_id] %>
  <%= label_tag :from %>
  <%= datetime_field_tag :time_min, params[:time_min] %>
  <%= label_tag :to %>
  <%= datetime_field_tag :time_max, params[:time_max] %>
  <%= submit_tag 'Filter' %>
<% end %>
<ul>
  <% @events.items.each do |event| %>
    <li>
      <% attendees = event.attendees.map(&:email).join(', ') if event.attendees %>
      <% date = event.start.date_time || event.start.date.to_date %>
      <%= event.summary %> (<%= time_tag date %>) <%= "- #{attendees}" if attendees %>
    </li>
  <% end %>
</ul>

app/views/calendars/index.html.erb
<h1>Calendars</h1>
<ul>
  <% @calendar_list.items.each do |calendar| %>
    <li>
      <%= link_to calendar.summary, events_calendars_path(calendar_id: calendar.id) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGoogle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>